spring:
  ai:
    mcp:
      server:
        enabled: true
        name: profiles-generator-mcp-sse
        version: 0.0.1
        type: SYNC
        instructions: "This server provides Profiles data"
        capabilities:
          resource: false
          tool: true
          prompt: false
          completion: false
        sse-message-endpoint: /mcp/message

server:
  port: 8085
